# Generated by Django 5.0.3 on 2024-04-06 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'db_table': 'category_product',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Color de producto',
                'verbose_name_plural': 'Colores de productos',
                'db_table': 'color_product',
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de productos',
                'db_table': 'type_product',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Precio')),
                ('measure', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Medida')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='products/', verbose_name='Imagen')),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categoryproduct', verbose_name='Categoría de producto')),
                ('color_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.colorproduct', verbose_name='Color de producto')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.typeproduct', verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
    ]
