# Generated by Django 5.0.3 on 2024-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category_product_typeproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='types', to='product.categoryproduct', verbose_name='Categoría'),
        ),
    ]
