# Generated by Django 5.0.3 on 2024-04-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_typeproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categoryproduct', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.colorproduct', verbose_name='Color de producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.typeproduct', verbose_name='Tipo de producto'),
        ),
    ]
