# Generated by Django 5.0.3 on 2024-04-05 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Numero de documento')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True, verbose_name='Correo electronico')),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Contraseña')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
            },
        ),
    ]
