# Generated by Django 5.0.3 on 2024-04-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='Pedido',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AlterField(
            model_name='order',
            name='desing',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Diseño'),
        ),
    ]
